# Generated by Django 4.2.5 on 2024-02-10 13:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricName', models.CharField(blank=True, default='', max_length=100)),
                ('fabricDescription', models.CharField(blank=True, default='', max_length=1000)),
                ('GSM', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('fabricType', models.CharField(blank=True, default='', max_length=100)),
                ('material', models.CharField(blank=True, default='', max_length=100)),
                ('sampleImages', models.ImageField(blank=True, default='', upload_to=api.models.sample_path)),
                ('labels', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
