# Generated by Django 4.2.5 on 2024-02-14 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_basemodel_timestamp_alter_fabric_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 14, 15, 22, 56, 521909)),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 14, 15, 22, 56, 522919)),
        ),
    ]
