# Generated by Django 4.2.5 on 2024-02-15 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_basemodel_timestamp_alter_fabric_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 15, 10, 44, 9, 704884)),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 15, 10, 44, 9, 705880)),
        ),
        migrations.CreateModel(
            name='YoloModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(blank=True, default='', max_length=100)),
                ('epochs', models.IntegerField(default=10)),
                ('imgsz', models.IntegerField(default=640)),
                ('baseModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.basemodel')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datasets')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fabric')),
            ],
        ),
    ]
