# Generated by Django 4.2.5 on 2024-02-15 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_basemodel_timestamp_alter_fabric_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotatorId', models.CharField(blank=True, default='', max_length=100)),
                ('annotatorName', models.CharField(blank=True, default='', max_length=100)),
                ('annotatorEmail', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 15, 15, 51, 48, 963885)),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 15, 15, 51, 48, 963885)),
        ),
    ]
