# Generated by Django 4.2.5 on 2024-03-07 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_basemodel_timestamp_alter_fabric_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 7, 14, 46, 37, 548606)),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 7, 14, 46, 37, 549610)),
        ),
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('centroid', models.CharField(blank=True, default='', max_length=100)),
                ('boundingBox', models.CharField(blank=True, default='', max_length=100)),
                ('imageRaw', models.CharField(blank=True, default='', max_length=500)),
                ('imageAnnotated', models.CharField(blank=True, default='', max_length=500)),
                ('confidence', models.FloatField(blank=True, default=0.0)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fabric')),
            ],
        ),
    ]
